import type { ExpenseResponse } from '@/api/expenses/type';

// export interface Travel {
//   id: number;
//   name: string;
//   imageUrl: string;
// }

// export interface Budget {
//   id: number;
//   name: string;
//   countryCode: string;
// }

// interface Company {
//   name: string;
//   iconUrl: string;
// }

// interface Card {
//   company: Company;
//   label: string;
//   lastDigits: string;
// }

// export interface PaymentMethod {
//   isCash: boolean;
//   card: Card | null;
// }

// export interface Expense {
//   expenseId: number;
//   occurredAt: string; // ISO 8601 형식의 날짜 문자열
//   merchantName: string; // 거래처
//   categoryCode: CategoryType; // 카테고리
//   localCurrencyCode: string; // 현지통화
//   localCurrencyAmount: number; // 현지금액
//   standardCurrency: string; // 기준통화
//   standardAmount: number; // 기준금액
//   exchangeRate: number; // 환율
//   paymentMethod: PaymentMethod; // 결제수단
//   travel: Travel;
//   memo: string | null;
//   file: string;
// }

export function getData(): ExpenseResponse[] {
  return [
    {
      expenseId: 680,
      accountBookId: 900019,
      travelId: null,
      merchantName: '7-Eleven',
      displayMerchantName: '7-Eleven',
      category: 5,
      paymentMethod: {
        isCash: false,
        card: {
          company: 'SHINHAN',
          label: 'My Card 2',
          lastDigits: '0102',
        },
      },
      occurredAt: '2026-02-16T21:53:19Z',
      localCurrencyAmount: 14521.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 14521.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-33',
      source: 'MANUAL',
      approvalNumber: 'APP0021033',
      cardNumber: '0033',
      fileLink: null,
    },
    {
      expenseId: 15280,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Yogiyo',
      displayMerchantName: 'Yogiyo',
      category: 5,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-16T19:43:29Z',
      localCurrencyAmount: 14531.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 14531.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-763',
      source: 'MANUAL',
      approvalNumber: 'APP0021763',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 7980,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Lotte Mart',
      displayMerchantName: 'Lotte Mart',
      category: 9,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-16T08:48:24Z',
      localCurrencyAmount: 14526.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 14526.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-398',
      source: 'MANUAL',
      approvalNumber: 'APP0021398',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 16320,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'GS25',
      displayMerchantName: 'GS25',
      category: 7,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-15T23:15:45Z',
      localCurrencyAmount: 21655.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 21655.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-815',
      source: 'IMAGE_RECEIPT',
      approvalNumber: 'APP0021815',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 9020,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Starbucks',
      displayMerchantName: 'Starbucks',
      category: 2,
      paymentMethod: {
        isCash: false,
        card: {
          company: 'TOSS',
          label: 'My Card 1',
          lastDigits: '0101',
        },
      },
      occurredAt: '2026-02-15T12:20:40Z',
      localCurrencyAmount: 10.0,
      localCurrencyCode: 'USD',
      baseCurrencyAmount: 13000.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-450',
      source: 'IMAGE_RECEIPT',
      approvalNumber: 'APP0021450',
      cardNumber: '0450',
      fileLink: null,
    },
    {
      expenseId: 1720,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Yes24',
      displayMerchantName: 'Yes24',
      category: 7,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-15T01:25:35Z',
      localCurrencyAmount: 21645.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 21645.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-85',
      source: 'IMAGE_RECEIPT',
      approvalNumber: 'APP0021085',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 10060,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Paris Baguette',
      displayMerchantName: 'Paris Baguette',
      category: 6,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-14T16:52:56Z',
      localCurrencyAmount: 28774.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 28774.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-502',
      source: 'IMAGE_APP_CAPTURE',
      approvalNumber: 'APP0021502',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 2760,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Incheon Airport',
      displayMerchantName: 'Incheon Airport',
      category: 1,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-14T05:57:51Z',
      localCurrencyAmount: 28769.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 28769.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-137',
      source: 'IMAGE_APP_CAPTURE',
      approvalNumber: 'APP0021137',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 17360,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Spotify',
      displayMerchantName: 'Spotify',
      category: 1,
      paymentMethod: {
        isCash: false,
        card: {
          company: 'SHINHAN',
          label: 'My Card 2',
          lastDigits: '0102',
        },
      },
      occurredAt: '2026-02-14T03:47:01Z',
      localCurrencyAmount: 28779.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 28779.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-867',
      source: 'IMAGE_APP_CAPTURE',
      approvalNumber: 'APP0021867',
      cardNumber: '0867',
      fileLink: null,
    },
    {
      expenseId: 11100,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Kakao T',
      displayMerchantName: 'Kakao T',
      category: 4,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-13T20:24:12Z',
      localCurrencyAmount: 35898.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 35898.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-554',
      source: 'MANUAL',
      approvalNumber: 'APP0021554',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 3800,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Daiso',
      displayMerchantName: 'Daiso',
      category: 0,
      paymentMethod: {
        isCash: false,
        card: {
          company: 'SHINHAN',
          label: 'My Card 2',
          lastDigits: '0102',
        },
      },
      occurredAt: '2026-02-13T09:29:07Z',
      localCurrencyAmount: 35893.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 35893.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-189',
      source: 'MANUAL',
      approvalNumber: 'APP0021189',
      cardNumber: '0189',
      fileLink: null,
    },
    {
      expenseId: 18400,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'SK Energy',
      displayMerchantName: 'SK Energy',
      category: 0,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-13T07:19:17Z',
      localCurrencyAmount: 35903.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 35903.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-919',
      source: 'MANUAL',
      approvalNumber: 'APP0021919',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 4840,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'McDonalds',
      displayMerchantName: 'McDonalds',
      category: 3,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-12T13:01:23Z',
      localCurrencyAmount: 1241.0,
      localCurrencyCode: 'JPY',
      baseCurrencyAmount: 11169.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-241',
      source: 'CSV',
      approvalNumber: 'APP0021241',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 19440,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Coupang Eats',
      displayMerchantName: 'Coupang Eats',
      category: 3,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-12T11:51:33Z',
      localCurrencyAmount: 1971.0,
      localCurrencyCode: 'JPY',
      baseCurrencyAmount: 17739.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-971',
      source: 'CSV',
      approvalNumber: 'APP0021971',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 12140,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Emart',
      displayMerchantName: 'Emart',
      category: 8,
      paymentMethod: {
        isCash: false,
        card: {
          company: 'TOSS',
          label: 'My Card 1',
          lastDigits: '0101',
        },
      },
      occurredAt: '2026-02-12T00:56:28Z',
      localCurrencyAmount: 43022.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 43022.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-606',
      source: 'CSV',
      approvalNumber: 'APP0021606',
      cardNumber: '0606',
      fileLink: null,
    },
    {
      expenseId: 5880,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Baskin Robbins',
      displayMerchantName: 'Baskin Robbins',
      category: 5,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-11T17:33:39Z',
      localCurrencyAmount: 50141.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 50141.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-293',
      source: 'MANUAL',
      approvalNumber: 'APP0021293',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 13180,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Apple',
      displayMerchantName: 'Apple',
      category: 9,
      paymentMethod: {
        isCash: true,
        card: null,
      },
      occurredAt: '2026-02-11T04:28:44Z',
      localCurrencyAmount: 50146.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 50146.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-658',
      source: 'MANUAL',
      approvalNumber: 'APP0021658',
      cardNumber: null,
      fileLink: null,
    },
    {
      expenseId: 6920,
      accountBookId: 900019,
      travelId: null,
      merchantName: 'Uber',
      displayMerchantName: 'Uber',
      category: 7,
      paymentMethod: {
        isCash: false,
        card: {
          company: 'SHINHAN',
          label: 'My Card 2',
          lastDigits: '0102',
        },
      },
      occurredAt: '2026-02-10T21:05:55Z',
      localCurrencyAmount: 57265.0,
      localCurrencyCode: 'KRW',
      baseCurrencyAmount: 57265.0,
      baseCurrencyCode: 'KRW',
      memo: 'seed memo U10-B1-345',
      source: 'IMAGE_RECEIPT',
      approvalNumber: 'APP0021345',
      cardNumber: '0345',
      fileLink: null,
    },
  ];
}
