title: "[Poll] "
body:
  - type: markdown
    attributes:
      value: |
        이 카테고리는 팀 의견을 투표로 수렴하기 위한 공간입니다.
        ※ 실제 '투표 선택지'는 Discussion 작성 화면에서 Poll 옵션으로 추가해야 합니다.
        아래 템플릿은 투표의 맥락/기준을 명확히 하기 위한 내용입니다.

  - type: input
    id: topic
    attributes:
      label: 투표 주제
      description: 하나의 쟁점에 집중해서 적어 주세요.
      placeholder: "예) API 인증 방식: JWT vs Session"
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 배경/필요성
      description: 왜 결정이 필요한지, 지금까지 어떤 논의가 있었는지
      placeholder: |
        - 현재 상황:
        - 결정이 필요한 이유:
        - 관련 링크/토론:
    validations:
      required: true

  - type: textarea
    id: options
    attributes:
      label: 선택지 정의
      description: 투표 선택지를 정확히 적어 주세요(이걸 그대로 Poll 옵션에 복사).
      placeholder: |
        - 선택지 A: (짧고 명확하게)
        - 선택지 B:
        - 선택지 C(있다면):

    validations:
      required: true

  - type: textarea
    id: criteria
    attributes:
      label: 판단 기준
      description: 어떤 기준으로 투표해야 하는지(성능/개발속도/리스크/운영 등)
      placeholder: |
        - 기준 1:
        - 기준 2:
        - 기준 3:

  - type: input
    id: deadline
    attributes:
      label: 투표 마감 시점
      description: 언제까지 투표/결정할지
      placeholder: "예) 2026-02-05 18:00 (KST)"
    validations:
      required: true
