/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InitRouteImport } from './routes/init'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InitRoute = InitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/home': typeof HomeRoute
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/setting': typeof SettingRoute
  '/travel': typeof TravelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/home': typeof HomeRoute
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/setting': typeof SettingRoute
  '/travel': typeof TravelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/home': typeof HomeRoute
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/setting': typeof SettingRoute
  '/travel': typeof TravelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/home'
    | '/init'
    | '/login'
    | '/setting'
    | '/travel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/home' | '/init' | '/login' | '/setting' | '/travel'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/home'
    | '/init'
    | '/login'
    | '/setting'
    | '/travel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  HomeRoute: typeof HomeRoute
  InitRoute: typeof InitRoute
  LoginRoute: typeof LoginRoute
  SettingRoute: typeof SettingRoute
  TravelRoute: typeof TravelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/init': {
      id: '/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof InitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  HomeRoute: HomeRoute,
  InitRoute: InitRoute,
  LoginRoute: LoginRoute,
  SettingRoute: SettingRoute,
  TravelRoute: TravelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
