/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppTravelRouteImport } from './routes/_app/travel'
import { Route as AppSettingRouteImport } from './routes/_app/setting'
import { Route as AppReportRouteImport } from './routes/_app/report'
import { Route as AppInitRouteImport } from './routes/_app/init'
import { Route as AppHomeRouteImport } from './routes/_app/home'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppTravelRoute = AppTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingRoute = AppSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppInitRoute = AppInitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/home': typeof AppHomeRoute
  '/init': typeof AppInitRoute
  '/report': typeof AppReportRoute
  '/setting': typeof AppSettingRoute
  '/travel': typeof AppTravelRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/home': typeof AppHomeRoute
  '/init': typeof AppInitRoute
  '/report': typeof AppReportRoute
  '/setting': typeof AppSettingRoute
  '/travel': typeof AppTravelRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/init': typeof AppInitRoute
  '/_app/report': typeof AppReportRoute
  '/_app/setting': typeof AppSettingRoute
  '/_app/travel': typeof AppTravelRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/init'
    | '/report'
    | '/setting'
    | '/travel'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/init' | '/report' | '/setting' | '/travel' | '/login'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/home'
    | '/_app/init'
    | '/_app/report'
    | '/_app/setting'
    | '/_app/travel'
    | '/_auth/login'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/travel': {
      id: '/_app/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof AppTravelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setting': {
      id: '/_app/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AppSettingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/init': {
      id: '/_app/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof AppInitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppInitRoute: typeof AppInitRoute
  AppReportRoute: typeof AppReportRoute
  AppSettingRoute: typeof AppSettingRoute
  AppTravelRoute: typeof AppTravelRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppInitRoute: AppInitRoute,
  AppReportRoute: AppReportRoute,
  AppSettingRoute: AppSettingRoute,
  AppTravelRoute: AppTravelRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
